shell:
  program: /usr/bin/tmux
  args:
    - new-session
    - -A
    - -D
    - -s
    - new

scrolling:
  # Maximum number of lines in the scrollback buffer.
  # Specifying '0' will disable scrolling.
  history: 100000

# Font configuration
font:
  # Normal (roman) font face
  normal:
    # Font family
    #
    # Default:
    #   - (macOS) Menlo
    #   - (Linux/BSD) monospace
    #   - (Windows) Consolas
    # family: Source Code Pro
    # family: CodeNewRoman Nerd Font
    # family: RobotoMono Nerd Font
    # family: Hack
    # family: JetBrains Mono
    # family: UbuntuMono Nerd Font
    # family: Monofur Nerd Font
    # family: TerminessTTF Nerd Font
    # family: Mononoki Nerd Font
    family: FiraCode Nerd Font
    
    # The `style` can be specified to pick a specific face.
    style: Regular

  # Bold font face
  bold:
    # Font family
    #
    # If the bold family is not specified, it will fall back to the
    # value specified for the normal font.
    # family: Source Code Pro
    # family: CodeNewRoman Nerd Font
    # family: RobotoMono Nerd Font
    # family: Hack
    # family: JetBrains Mono
    # family: UbuntuMono Nerd Font
    # family: Monofur Nerd Font
    # family: TerminessTTF Nerd Font
    # family: Mononoki Nerd Font
    family: FiraCode Nerd Font
    # The `style` can be specified to pick a specific face.
    style: Bold

  # Italic font face
  italic:
    # Font family
    #
    # If the italic family is not specified, it will fall back to the
    # value specified for the normal font.
    # family: Source Code Pro
    # family: CodeNewRoman Nerd Font
    # family: RobotoMono Nerd Font
    # family: Hack
    # family: JetBrains Mono
    # family: UbuntuMono Nerd Font
    # family: Monofuritalic Nerd Font Mono
    # family: TerminessTTF Nerd Font
    # family: Mononoki Nerd Font
    family: FiraCode Nerd Font
    # The `style` can be specified to pick a specific face.
    style: Italic

  # Bold italic font face
  bold_italic:
    # Font family
    #
    # If the bold italic family is not specified, it will fall back to the
    # value specified for the normal font.
    # family: Source Code Pro
    # family: CodeNewRoman Nerd Font
    # family: RobotoMono Nerd Font
    # family: Hack
    # family: JetBrains Mono
    # family: UbuntuMono Nerd Font
    # family: Monofuritalic Nerd Font Mono
    # family: TerminessTTF Nerd Font
    # family: Mononoki Nerd Font
    family: FiraCode Nerd Font

    # The `style` can be specified to pick a specific face.
    style: Bold Italic

  # Point size
  size: 11.0

# If `true`, bold text is drawn using the bright color variants.
draw_bold_text_with_bright_colors: true

#######################################
##      START OF COLOR SCHEMES       ##
#######################################
schemes:
### One Dark ###
OneDark: &OneDark
  primary:
      background: '0x1e2127'
      foreground: '0xabb2bf'
  # Normal colors
  normal:
    black:   '0x1e2127'
    red:     '0xe06c75'
    green:   '0x98c379'
    yellow:  '0xd19a66'
    blue:    '0x61afef'
    magenta: '0xc678dd'
    cyan:    '0x56b6c2'
    white:   '0xabb2bf'
  # Bright colors
  bright:
    black:   '0x5c6370'
    red:     '0xe06c75'
    green:   '0x98c379'
    yellow:  '0xd19a66'
    blue:    '0x61afef'
    magenta: '0xc678dd'
    cyan:    '0x56b6c2'
    white:   '0xffffff'

tokyo-night: &tokyo-night
  # Default colors
  primary:
    background: '0x1a1b26'
    foreground: '0xa9b1d6'

  # Normal colors
  normal:
    black:   '0x32344a'
    red:     '0xf7768e'
    green:   '0x9ece6a'
    yellow:  '0xe0af68'
    blue:    '0x7aa2f7'
    magenta: '0xad8ee6'
    cyan:    '0x449dab'
    white:   '0x787c99'

  # Bright colors
  bright:
    black:   '0x444b6a'
    red:     '0xff7a93'
    green:   '0xb9f27c'
    yellow:  '0xff9e64'
    blue:    '0x7da6ff'
    magenta: '0xbb9af7'
    cyan:    '0x0db9d7'
    white:   '0xacb0d0'

tokyo-night-storm: &tokyo-night-storm
  # Default colors
  primary:
    background: '0x24283b'
    foreground: '0xa9b1d6'

  # Normal colors
  normal:
    black:   '0x32344a'
    red:     '0xf7768e'
    green:   '0x9ece6a'
    yellow:  '0xe0af68'
    blue:    '0x7aa2f7'
    magenta: '0xad8ee6'
    cyan:    '0x449dab'
    white:   '0x9699a8'

  # Bright colors
  bright:
    black:   '0x444b6a'
    red:     '0xff7a93'
    green:   '0xb9f27c'
    yellow:  '0xff9e64'
    blue:    '0x7da6ff'
    magenta: '0xbb9af7'
    cyan:    '0x0db9d7'
    white:   '0xacb0d0'
######################################################################
## SET THEME: Choose ONE color scheme from those in the above list. ##
## ###################################################################
# Available themes are:
# *OneDark
# *tokyo-night
# *tokyo-night-storm
colors: *tokyo-night
