#!/usr/bin/env sh

# Check if inside a tmux session
if [ -n "$TMUX" ]; then
    # Open nvim in a new tmux window
    tmux new-window "nvim ."
else
    # If not in tmux, just open nvim in the current directory
    nvim .
fi
